In [4]:
age =16
if age >= 18:
  print("Eligible")
else:
    print("Not Eligible")

Not Eligible
16

In [3]:
var = True
print(type(var))

<class 'bool'>

In [35]:
marks =72
if marks >= 90:
  print("A+")
elif marks >=75:
  print("B")
elif marks>=50:
    print("C")
else:
  print("Fail")

C

In [9]:
age =25
fare=80
if age>=18 and fare>=50:
  print("Condition satisfied")

Condition satisfied

In [11]:
age =25
survived=1
if age>=18:
 if survived==1:
   print("Adult advisor")

Adult advisor

#LISTS
ordered,
Indexed,
Mutable,can contain duplicate values use square bracktes[]

In [13]:
ages=[22,38,26,35,35]
names =["Samriddhi","Shreyali","Vishal"]
mixed =[10,"python",3.5,True]
print(ages)
print(names)
print(mixed)

[22, 38, 26, 35, 35]
['Samriddhi', 'Shreyali', 'Vishal']
[10, 'python', 3.5, True]

indexing and slicing

In [25]:
print(age[-1])
print(names[-1])

TypeError: 'int' object is not subscriptable

In [19]:
print(ages[::2])

[22, 26, 35]

In [20]:
print(ages[::-1])

[35, 35, 26, 38, 22]

In [22]:
ages=[22,38,26,35,35]
ages[1]=27
print(ages)

[22, 27, 26, 35, 35]

In [23]:
print(names)

['Samriddhi', 'Shreyali', 'Vishal']

In [24]:
names.append("Vani")
print(names)

['Samriddhi', 'Shreyali', 'Vishal', 'Vani']

In [26]:
names.insert(1,"Sachin")
print(names)

['Samriddhi', 'Sachin', 'Shreyali', 'Vishal', 'Vani']

In [27]:
names.extend(["Neha","Rishab"])
print(names)

['Samriddhi', 'Sachin', 'Shreyali', 'Vishal', 'Vani', 'Neha', 'Rishab']

In [28]:
names.remove("Neha")
print(names)

['Samriddhi', 'Sachin', 'Shreyali', 'Vishal', 'Vani', 'Rishab']

In [38]:
numbers=[40,10,30,20,10]
print(len(numbers))

5

In [39]:
print(numbers.count(10))

2

In [46]:
print(10 in numbers)

True

In [47]:
print(max(numbers))

30

In [48]:
print(min(numbers))

10

In [49]:
numbers.sort()

In [50]:
print(numbers)

[10, 30]

In [51]:
print(sum(numbers))

40

In [52]:
numbers.reverse()
print(numbers)

[30, 10]

Nested List

In [60]:
students =[
    ["samriddi",21,"CSE"],
    ["shreyali",22,"ME"],
    ["vishal",20,"ECE"]
]
print(students[0])

['samriddi', 21, 'CSE']

In [61]:
print(students[0])

['samriddi', 21, 'CSE']

In [62]:
print(students[0][0])

samriddi

In [64]:
print(students[2][2])

ECE

In [65]:
students[0][1]=22
print(students)

[['samriddi', 22, 'CSE'], ['shreyali', 22, 'ME'], ['vishal', 20, 'ECE']]

In [66]:
students.append(["Sachin",21,"IT"])
print(students)

[['samriddi', 22, 'CSE'], ['shreyali', 22, 'ME'], ['vishal', 20, 'ECE'], ['Sachin', 21, 'IT']]

In [68]:
students[0].append("Mathura")

In [69]:
print(students)

[['samriddi', 22, 'CSE', 'Mathura', 'Mathura'], ['shreyali', 22, 'ME'], ['vishal', 20, 'ECE'], ['Sachin', 21, 'IT']]

In [80]:
for student in students:
  for value in students:
   print(value)

a

In [83]:
marks=[35,62,81,45,90]
for mark in marks:
  if mark >= 50:
    print(mark,"PASS")
  else:
    print(mark,"FAIL")

35 FAIL
62 PASS
81 PASS
45 FAIL
90 PASS

In [88]:
import pandas as pd

In [89]:
data ={
    "Customer ID":[101,102,103,104,104],
    "NAME":["ALICE","BOB","CHARLIE","DAVID","JOHN"],
    "AGE":[25,30,45,28,41],
    "AMOUNT":[2500,5600,7800,1500,9800],
    "RATING":[4.2,4.5,4.6,4.3,4.7]
}

In [90]:
df=pd.DataFrame(data)
print(df)

   Customer ID     NAME  AGE  AMOUNT  RATING
0          101    ALICE   25    2500     4.2
1          102      BOB   30    5600     4.5
2          103  CHARLIE   45    7800     4.6
3          104    DAVID   28    1500     4.3
4          104     JOHN   41    9800     4.7

In [93]:
df.iloc[0]

Customer ID      101
NAME           ALICE
AGE               25
AMOUNT          2500
RATING           4.2
Name: 0, dtype: object

In [94]:
df.iloc[0:3]

   Customer ID     NAME  AGE  AMOUNT  RATING
0          101    ALICE   25    2500     4.2
1          102      BOB   30    5600     4.5
2          103  CHARLIE   45    7800     4.6

In [95]:
df.iloc[0:5,0:3]

   Customer ID     NAME  AGE
0          101    ALICE   25
1          102      BOB   30
2          103  CHARLIE   45
3          104    DAVID   28
4          104     JOHN   41

In [97]:
df.loc[df["Amount"] >500,["CUSTOMER ID","RATING"]]

KeyError: 'Amount'